# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php82_node

stages:
  - prepare # prepare the cache
  - check # check the codestyles
  - test
  - deploy


prepare_cache:
  stage: prepare
  script:
    # Install composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar validate
    - php composer.phar install
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - composer.phar
      - vendor/*

lint:
  stage: check
  script:
    # lint recursive
    - find app/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  dependencies: []

phpmd:
  stage: check
  script:
    - vendor/bin/phpmd app/ text phpmd.xml.dist
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

code-style:
  stage: check
  script:
    - composer cs
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

# We check the content with vale
vale:
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdkato/vale
    entrypoint: [""]
  stage: check
  script:
    - /bin/vale --config=tools/vale/.vale.ini README.md
  needs: []
  dependencies: []

test:
  stage: test
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="app/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

test_83:
  stage: test
  image: registry.gitlab.com/tjvb/phpimages:php83_node
  script:
    - composer install
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="app/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - vendor/bin/dep deploy -vvv
  environment: production
  resource_group: production
  only:
    - main
