# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php82

stages:
  - prepare # prepare the cache
  - check # check the codestyles
  - deploy


prepare_cache:
  stage: prepare
  script:
    # Install composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar validate
    - php composer.phar install
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - composer.phar
      - vendor/*

lint:
  stage: check
  script:
    # lint recursive
    - find app/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  dependencies: []

pint:
  stage: check
  script:
    - vendor/bin/pint
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

phpmd:
  stage: check
  script:
    - vendor/bin/phpmd app/ text phpmd.xml.dist
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - vendor/bin/dep deploy -vvv
  environment: production
  resource_group: production
  only:
    - main
